cmake_minimum_required(VERSION 3.3)

string(REPLACE "," ";" PACKAGES ${BUILD})

function(y_download _url _sha1)
  string(REGEX REPLACE "^.*/([^/]+)$" "\\1" _name ${_url})
  message(STATUS "Downloading ${_name}")
  set(_path "${CMAKE_BINARY_DIR}/${_name}")
  if(EXISTS ${_path})
    file(SHA1 ${_path} _existing_sha1)
    if(${_sha1} STREQUAL ${_existing_sha1})
      return()
    endif()
    file(REMOVE ${_path})
  endif()
  file(DOWNLOAD ${_url} ${_path} TLS_VERIFY ON EXPECTED_HASH SHA1=${_sha1})
endfunction()

macro(_y_add_package _package)
  if(_y_packages)
    set(_y_packages "${_y_packages};${_package}" PARENT_SCOPE)
  else()
    set(_y_packages "${_package}" PARENT_SCOPE)
  endif()
endmacro()

function(y_package _package)
  if("all" IN_LIST PACKAGES)
    _y_add_package(${_package})
  elseif(${_package} IN_LIST PACKAGES)
    cmake_parse_arguments(_arg "" "" "REQUIRES" ${ARGN})
    foreach(_dependency ${_arg_REQUIRES})
      if(NOT ${_dependency} IN_LIST _y_packages)
        message(STATUS "Add: ${_dependency}")
        list(APPEND _dependencies ${_dependency})
      endif()
    endforeach()
    if(_dependencies)
      set(PACKAGES "${PACKAGES};${_dependencies}" PARENT_SCOPE)
    endif()
    _y_add_package(${_package})
  endif()
endfunction()

y_package(libvorbis REQUIRES libogg)
y_package(libjpeg REQUIRES nasm)
y_package(libpng REQUIRES nasm zlib)
y_package(libogg)
y_package(nasm)
y_package(openal)
y_package(opengl)
y_package(zlib)

if("nasm" IN_LIST _y_packages)
  y_download("https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-win64.zip" "149a814fa53980976a7fc081231f59cfbcd02543")
endif()

if("openal" IN_LIST _y_packages)
  y_download("https://openal.org/downloads/oalinst.zip" "45e08368c6755c58902b7746ff3e51ad2df8a8b8")
  y_download("http://openal-soft.org/openal-binaries/openal-soft-1.18.2-bin.zip" "0d2edd1b77cbb998f12e064d0eefea3508446776")
endif()

if("zlib" IN_LIST _y_packages)
  y_download("https://zlib.net/zlib-1.2.11.tar.xz" "e1cb0d5c92da8e9a8c2635dfa249c341dfd00322")
endif()

if("libjpeg" IN_LIST _y_packages)
  y_download("https://downloads.sourceforge.net/project/libjpeg-turbo/1.5.3/libjpeg-turbo-1.5.3.tar.gz" "87ebf4cab2bb27fcb8e7ccb18ec4eb680e1f2c2d")
endif()

if("libpng" IN_LIST _y_packages)
  y_download("https://downloads.sourceforge.net/project/libpng/libpng16/1.6.35/libpng-1.6.35.tar.xz" "0df1561aa1da610e892239348970d574b14deed0")
endif()
