version: 0.0.{build}-{branch}
image: Visual Studio 2017
shallow_clone: true

branches:
  only:
    - develop
    - master

environment:
  matrix:
    - RENDERER: null
      ARCHITECTURE: x86
      DLL: OFF
      BENCHMARK: ON
      Y3: catch2,freetype,jpeg,vorbis
    - RENDERER: null
      ARCHITECTURE: amd64
      DLL: OFF
      BENCHMARK: ON
      Y3: catch2,freetype,jpeg,vorbis
    - RENDERER: opengl
      ARCHITECTURE: amd64
      DLL: ON
      BENCHMARK: OFF
      Y3: catch2,freetype,vorbis,opengl
    - RENDERER: opengl
      ARCHITECTURE: amd64
      DLL: OFF
      BENCHMARK: OFF
      Y3: catch2,freetype,vorbis,opengl

cache:
  - _3rdparty\.cache

install:
  - cmd: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCHITECTURE%
      cinst ninja
      set PREFIX_DIR=%APPVEYOR_BUILD_FOLDER%\_3rdparty
      if not exist %PREFIX_DIR% mkdir %PREFIX_DIR%
      cd %PREFIX_DIR%
      cmake -DBUILD=%Y3% -DCONFIG=RelWithDebInfo,Debug -P %APPVEYOR_BUILD_FOLDER%\cmake\y3\get.cmake
      rmdir /s /q .build
      rmdir /s /q .trash

build_script:
  - cmd: |
      set DEBUG_DIR=%APPVEYOR_BUILD_FOLDER%\_debug
      set RELWITHDEBINFO_DIR=%APPVEYOR_BUILD_FOLDER%\_relwithdebinfo
      set INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\_install
      mkdir %DEBUG_DIR% && cd %DEBUG_DIR%
      cmake -G"Ninja" %APPVEYOR_BUILD_FOLDER% -DBUILD_BENCHMARKS=%BENCHMARK% -DBUILD_EXAMPLES=ON -DBUILD_SHARED_LIBS=%DLL% -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% -DCMAKE_PREFIX_PATH=%PREFIX_DIR% -DY_RENDERER=%RENDERER%
      cmake --build .
      cd ..
      mkdir %RELWITHDEBINFO_DIR% && cd %RELWITHDEBINFO_DIR%
      cmake -G"Ninja" %APPVEYOR_BUILD_FOLDER% -DBUILD_BENCHMARKS=%BENCHMARK% -DBUILD_EXAMPLES=ON -DBUILD_SHARED_LIBS=%DLL% -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% -DCMAKE_PREFIX_PATH=%PREFIX_DIR% -DY_RENDERER=%RENDERER%
      cmake --build .
      cmake --build . --target install
      cd ..

test_script:
  - cmd: |
      cd %DEBUG_DIR%
      ctest --output-on-failure
      cd ..
      cd %RELWITHDEBINFO_DIR%
      ctest --output-on-failure
      if "%BENCHMARK%"=="ON" bin\benchmark_jpeg.exe %APPVEYOR_BUILD_FOLDER%\examples\tetrium\data\textures\background.jpeg
