version: 0.0.{build}-{branch}
image: Visual Studio 2017
shallow_clone: true

skip_commits:
  files:
    - docs/
    - .clang-format
    - .gitignore
    - .travis.yml
    - LICENSE
    - README.md

environment:
  matrix:
    - RENDERER: null
      DLL: OFF
      BENCHMARK: ON
      Y3: catch2,freetype,jpeg,vorbis
      GENERATOR: Visual Studio 15 2017
    - RENDERER: null
      DLL: OFF
      BENCHMARK: ON
      Y3: catch2,freetype,jpeg,vorbis
      GENERATOR: Visual Studio 15 2017 Win64
    - RENDERER: opengl
      DLL: ON
      BENCHMARK: OFF
      Y3: catch2,freetype,vorbis,opengl
      GENERATOR: Visual Studio 15 2017 Win64
    - RENDERER: opengl
      DLL: OFF
      BENCHMARK: OFF
      Y3: catch2,freetype,vorbis,opengl
      GENERATOR: Visual Studio 15 2017 Win64

cache:
  - _3rdparty\.cache

install:
  - cmd: |
      set PREFIX_DIR=%APPVEYOR_BUILD_FOLDER%\_3rdparty
      if not exist %PREFIX_DIR% mkdir %PREFIX_DIR%
      cd %PREFIX_DIR%
      cmake -DBUILD=%Y3% "-DGENERATOR=%GENERATOR%" -P %APPVEYOR_BUILD_FOLDER%\cmake\y3\get.cmake
      rmdir /s /q .build
      rmdir /s /q .trash

build_script:
  - cmd: |
      set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\_build
      mkdir %BUILD_DIR% && cd %BUILD_DIR%
      cmake -G "%GENERATOR%" %APPVEYOR_BUILD_FOLDER% -DBUILD_BENCHMARKS=%BENCHMARK% -DBUILD_EXAMPLES=ON -DBUILD_SHARED_LIBS=%DLL% -DBUILD_TESTS=ON -DCMAKE_PREFIX_PATH=%PREFIX_DIR% -DY_RENDERER=%RENDERER%
      cmake --build . --config Release -- /nologo /verbosity:minimal
      cmake --build . --config Debug -- /nologo /verbosity:minimal

test_script:
  - cmd: |
      ctest --build-config Release --output-on-failure
      ctest --build-config Debug --output-on-failure
      if "%BENCHMARK%"=="ON" bin\Release\benchmark_jpeg.exe %APPVEYOR_BUILD_FOLDER%\examples\tetrium\data\textures\background.jpeg
