version: 0.0.{build}-{branch}
image: Visual Studio 2017
shallow_clone: true

environment:
  matrix:
    - CONFIG: Release
      RENDERER: Null
    - CONFIG: Debug
      RENDERER: Null
    - CONFIG: Release
      RENDERER: OpenGL
    - CONFIG: Debug
      RENDERER: OpenGL

cache:
  - _3rdparty\.cache

install:
  - cmd: |
      set PREFIX_DIR=%APPVEYOR_BUILD_FOLDER%\_3rdparty
      if not exist %PREFIX_DIR% mkdir %PREFIX_DIR%
      cd %PREFIX_DIR%
      cmake -DBUILD=catch2,libjpeg,libpng,libvorbis,openal,opengl -DCONFIG=%CONFIG% -P %APPVEYOR_BUILD_FOLDER%\cmake\bootstrap.cmake

build_script:
  - cmd: |
      set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\_build
      mkdir %BUILD_DIR% && cd %BUILD_DIR%
      cmake -G "Visual Studio 15 2017 Win64" %APPVEYOR_BUILD_FOLDER% -DCMAKE_PREFIX_PATH=%PREFIX_DIR% -DY_BUILD_ALL=ON -DY_RENDERER=%RENDERER%
      cmake --build . --config %CONFIG% -- /nologo /verbosity:minimal

test_script:
  - cmd: |
      cmake --build . --config %CONFIG% --target check -- /nologo /verbosity:minimal
