version: 0.0.{build}-{branch}
image: Visual Studio 2017
shallow_clone: true

skip_commits:
  files:
    - docs/
    - .clang-format
    - .gitignore
    - .travis.yml
    - LICENSE
    - README.md

environment:
  matrix:
    - RENDERER: Null
    - RENDERER: OpenGL

cache:
  - _3rdparty\.cache

install:
  - cmd: |
      set PREFIX_DIR=%APPVEYOR_BUILD_FOLDER%\_3rdparty
      if not exist %PREFIX_DIR% mkdir %PREFIX_DIR%
      cd %PREFIX_DIR%
      cmake -DBUILD=catch2,jpeg,png,vorbis,openal,opengl -P %APPVEYOR_BUILD_FOLDER%\bootstrap\get.cmake
      rmdir /s /q .build
      rmdir /s /q .trash

build_script:
  - cmd: |
      set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\_build
      mkdir %BUILD_DIR% && cd %BUILD_DIR%
      cmake -G "Visual Studio 15 2017 Win64" %APPVEYOR_BUILD_FOLDER% -DCMAKE_PREFIX_PATH=%PREFIX_DIR% -DY_BUILD_ALL=ON -DY_RENDERER=%RENDERER%
      cmake --build . --config Release -- /nologo /verbosity:minimal
      cmake --build . --config Debug -- /nologo /verbosity:minimal

test_script:
  - cmd: |
      cmake --build . --config Release --target check -- /nologo /verbosity:minimal
      cmake --build . --config Debug --target check -- /nologo /verbosity:minimal
