version: 0.0.{build}-{branch}
image: Visual Studio 2017
shallow_clone: true

environment:
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14.1
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  matrix:
    - RENDERER: Null
    - RENDERER: OpenGL

install:
  - cmd: |
      dir /a:d /b C:\Libraries
      dir /a:d /b %BOOST_ROOT%

  - cmd: |
      set PREFIX=%APPVEYOR_BUILD_FOLDER%\_3rdparty

  - ps: |
      .\bootstrap\bootstrap.ps1 -prefix _3rdparty -libjpeg -libogg -libpng -libvorbis -nasm -openal -opengl -zlib

build_script:
  - cmd: |
      mkdir _build && cd _build
      cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_PREFIX_PATH=%PREFIX% -DY_ALL=ON -DY_RENDERER=%RENDERER%
      set PATH=%PATH%;%PREFIX%\bin
      cmake --build . --config Release -- /nologo /verbosity:minimal

test_script:
  - cmd: |
      set PATH=%PATH%;%BOOST_LIBRARYDIR%
      cmake --build . --config Release --target check -- /nologo /verbosity:minimal
