version: 0.0.{build}-{branch}
image: Visual Studio 2017
shallow_clone: true

environment:
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14.1
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  matrix:
    - RENDERER: Null
    - RENDERER: OpenGL

install:
  - cmd: |
      set PREFIX_DIR=%APPVEYOR_BUILD_FOLDER%\_3rdparty
      mkdir %PREFIX_DIR% && cd %PREFIX_DIR%
      call %APPVEYOR_BUILD_FOLDER%\bootstrap.bat

build_script:
  - cmd: |
      set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\_build
      mkdir %BUILD_DIR% && cd %BUILD_DIR%
      cmake -G "Visual Studio 15 2017 Win64" %APPVEYOR_BUILD_FOLDER% -DCMAKE_PREFIX_PATH=%PREFIX_DIR% -DY_ALL=ON -DY_RENDERER=%RENDERER%
      set PATH=%PATH%;%PREFIX_DIR%\bin
      cmake --build . --config Release -- /nologo /verbosity:minimal

test_script:
  - cmd: |
      set PATH=%PATH%;%BOOST_LIBRARYDIR%
      cmake --build . --config Release --target check -- /nologo /verbosity:minimal
