language: cpp
dist: trusty
sudo: false

git:
  depth: 1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libopenal-dev
      - libvorbis-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COVERAGE=1 GCC_VERSION=6

before_install:
  - if [ "${GCC_VERSION}" != "" ]; then export CC=gcc-$GCC_VERSION CXX=g++-$GCC_VERSION GCOV=gcov-$GCC_VERSION; fi

install:
  - mkdir ${TRAVIS_BUILD_DIR}/travis

  - mkdir ${TRAVIS_BUILD_DIR}/travis/boost && pushd ${TRAVIS_BUILD_DIR}/travis/boost
  - wget -q -O - http://downloads.sourceforge.net/project/boost/boost/1.64.0/boost_1_64_0.tar.bz2 | tar -xj --strip-components 1
  - ./bootstrap.sh
  - ./b2 headers
  - ./b2 -j2 --with-test
  - CMAKE_OPTIONS+=" -DBOOST_ROOT=$(pwd)"
  - popd

  - mkdir ${TRAVIS_BUILD_DIR}/travis/cmake && pushd ${TRAVIS_BUILD_DIR}/travis/cmake
  - wget -q --no-check-certificate -O - https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz | tar -xz --strip-components 1
  - export PATH=$(pwd)/bin:${PATH}
  - popd

script:
  - if [ "${COVERAGE}" = "1" ]; then CMAKE_OPTIONS+=" -DCOVERAGE=ON"; fi
  - cmake . $CMAKE_OPTIONS -DFIX_TRAVIS=ON -DWITH_EXAMPLES=ON -DWITH_EXTRA=ON -DWITH_TESTS=ON
  - cmake --build . -- -j2
  - ctest --output-on-failure

after_success:
  - if [ "${COVERAGE}" = "1" ]; then bash <(curl -s https://codecov.io/bash) -x $GCOV -a "-s `pwd`"; fi

notifications:
  email: false
