language: cpp

branches:
  only:
    - develop
    - master

git:
  depth: 1

matrix:
  include:

    - os: linux
      dist: xenial
      compiler: clang
      env: CLANG=7 CONFIG=Debug DLL=ON RENDERER=null Y3=catch2,cppcheck STATIC_ANALYSIS=1
      addons: &clang7_xcb
        apt:
          sources: &all_sources
            - ubuntu-toolchain-r-test
          packages:
            - libasound2-dev
            - libstdc++-8-dev
            - libvorbis-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - ninja-build

    - os: linux
      dist: xenial
      compiler: gcc
      env: GCC=9 CONFIG=Release DLL=OFF RENDERER=null Y3=catch2 BENCHMARK=1
      addons: &gcc9_xcb
        apt:
          sources: *all_sources
          packages:
            - g++-9
            - libasound2-dev
            - libvorbis-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - ninja-build

    - os: linux
      dist: xenial
      compiler: gcc
      env: GCC=9 CONFIG=Debug DLL=ON RENDERER=null Y3=catch2,lcov COVERAGE=1
      addons: *gcc9_xcb

    - os: linux
      dist: xenial
      compiler: gcc
      env: GCC=9 CONFIG=Release DLL=OFF RENDERER=opengl Y3=catch2
      addons: &gcc9_x11
        apt:
          sources: *all_sources
          packages:
            - g++-9
            - libasound2-dev
            - libgl-dev
            - libvorbis-dev
            - ninja-build

    - os: linux
      dist: xenial
      compiler: gcc
      env: GCC=9 CONFIG=Debug DLL=ON RENDERER=opengl Y3=catch2
      addons: *gcc9_x11

    - os: linux
      dist: xenial
      compiler: gcc
      env: GCC=9 CONFIG=Release DLL=OFF RENDERER=vulkan Y3=catch2,glslang,vulkan
      addons: *gcc9_xcb

    - os: linux
      dist: xenial
      compiler: gcc
      env: GCC=9 CONFIG=Debug DLL=ON RENDERER=vulkan Y3=catch2,glslang,vulkan
      addons: *gcc9_xcb

    - os: linux
      dist: xenial
      compiler: clang
      env: CLANG=7 CONFIG=Release DLL=OFF RENDERER=null Y3=catch2 BENCHMARK=1
      addons: &clang7_xcb
        apt:
          sources: *all_sources
          packages:
            - libasound2-dev
            - libstdc++-8-dev
            - libvorbis-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - ninja-build

    - os: linux
      dist: xenial
      compiler: clang
      env: CLANG=7 CONFIG=Release DLL=OFF RENDERER=opengl Y3=catch2
      addons: &clang7_x11
        apt:
          sources: *all_sources
          packages:
            - libasound2-dev
            - libgl-dev
            - libstdc++-8-dev
            - libvorbis-dev
            - ninja-build

    - os: linux
      dist: xenial
      compiler: clang
      env: CLANG=7 CONFIG=Debug DLL=ON RENDERER=opengl Y3=catch2
      addons: *clang7_x11

    - os: linux
      dist: xenial
      compiler: clang
      env: CLANG=7 CONFIG=Release DLL=OFF RENDERER=vulkan Y3=catch2,glslang,vulkan
      addons: *clang7_xcb

    - os: linux
      dist: xenial
      compiler: clang
      env: CLANG=7 CONFIG=Debug DLL=ON RENDERER=vulkan Y3=catch2,glslang,vulkan
      addons: *clang7_xcb

before_install:
  - if [ -n "${GCC}" ]; then export CC=gcc-${GCC} CXX=g++-${GCC} LDFLAGS=-fuse-ld=gold; fi
  - if [ -z "${BENCHMARK}" ] && [ -z "${COVERAGE}" ] && [ -z "${STATIC_ANALYSIS}" ]; then export NORMAL=1; fi

install:
  - mkdir "${HOME}/y3.prefix" && pushd "${HOME}/y3.prefix"
  - cmake -DBUILD=${Y3} -DCACHE="${HOME}/y3.cache" -DCONFIG=${CONFIG} -P "${TRAVIS_BUILD_DIR}/cmake/y3/get.cmake"
  - popd
  - if [ -n "${COVERAGE}" ]; then pip install --user codecov; fi

script:
  - if [ -n "${BENCHMARK}" ] || [ -n "${STATIC_ANALYSIS}" ]; then CMAKE_OPTIONS+=" -DBUILD_BENCHMARKS=ON"; fi
  - if [ -n "${COVERAGE}" ]; then CMAKE_OPTIONS+=" -DENABLE_COVERAGE=ON -DENABLE_COVERAGE_LCOV=ON"; fi
  - if [ -n "${NORMAL}" ] || [ -n "${STATIC_ANALYSIS}" ]; then CMAKE_OPTIONS+=" -DBUILD_EXAMPLES=ON"; fi
  - if [ -n "${NORMAL}" ]; then CMAKE_OPTIONS+=" -DENABLE_SANITIZERS=ON"; fi
  - if [ -n "${STATIC_ANALYSIS}" ]; then CMAKE_OPTIONS+=" -DENABLE_CLANG_FORMAT=ON -DENABLE_CLANG_TIDY=ON -DENABLE_CPPCHECK=ON -DENABLE_DIFF=ON"; fi
  - cmake -H. -B"${HOME}/yttrium.build" -G"Ninja" -DBUILD_SHARED_LIBS=${DLL} -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_INSTALL_PREFIX="${HOME}/yttrium.install" -DCMAKE_PREFIX_PATH="${HOME}/y3.prefix" -DY_RENDERER=${RENDERER} ${CMAKE_OPTIONS}
  - pushd "${HOME}/yttrium.build"
  - if [ -n "${STATIC_ANALYSIS}" ]; then cmake --build . --target cppcheck; fi
  - if [ -n "${STATIC_ANALYSIS}" ]; then cmake --build . --target tidy; fi
  - if [ -n "${STATIC_ANALYSIS}" ]; then cmake --build . --target format; fi
  - if [ -n "${STATIC_ANALYSIS}" ]; then cmake --build . --target diff; fi
  - if [ -z "${STATIC_ANALYSIS}" ]; then TERM=dumb cmake --build .; fi
  - if [ -z "${STATIC_ANALYSIS}" ]; then ctest --output-on-failure; fi
  - if [ -n "${NORMAL}" ]; then cmake --build . --target install; fi
  # lcov 1.14 doesn't work with GCC 9.x, see https://github.com/linux-test-project/lcov/issues/58
  #- if [ -n "${COVERAGE}" ]; then cmake --build . --target lcov; fi
  - popd

after_success:
  - if [ -n "${BENCHMARK}" ]; then "${HOME}/yttrium.build/bin/benchmark_jpeg" "${TRAVIS_BUILD_DIR}/examples/tetrium/data/textures/background.jpeg"; fi
  - if [ -n "${COVERAGE}" ]; then codecov --gcov-root "${HOME}/yttrium.build" --gcov-exec gcov-${GCC} --gcov-args "-s `pwd`"; fi

notifications:
  email: false
