language: cpp

git:
  depth: 1

matrix:
  include:

    - os: linux
      dist: focal
      compiler: clang
      env: RENDERER=null CONFIG=Debug CLANG=11 Y3=jpeg,vorbis ANALYZE=1
      addons:
        apt:
          packages:
            - clang-11
            - clang-format-11
            - clang-tidy-11
            - cppcheck
            - libasound2-dev
            - libstdc++-10-dev
            - libvorbis-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - nasm
            - ninja-build

    - os: linux
      dist: focal
      compiler: gcc
      env: RENDERER=opengl CONFIG=Release GCC=10 Y3=jpeg,vorbis
      addons: &gcc_x11
        apt:
          packages:
            - g++-10
            - libasound2-dev
            - libgl-dev
            - libvorbis-dev
            - yasm
            - ninja-build

    - os: linux
      dist: focal
      compiler: gcc
      env: RENDERER=opengl CONFIG=Debug GCC=10 Y3=jpeg,vorbis
      addons: *gcc_x11

    - os: linux
      dist: focal
      compiler: clang
      env: RENDERER=opengl CONFIG=Release CLANG=11 Y3=jpeg,vorbis
      addons: &clang_x11
        apt:
          packages:
            - clang-11
            - libasound2-dev
            - libgl-dev
            - libstdc++-10-dev
            - libvorbis-dev
            - nasm
            - ninja-build

    - os: linux
      dist: focal
      compiler: clang
      env: RENDERER=opengl CONFIG=Debug CLANG=11 Y3=jpeg,vorbis
      addons: *clang_x11

    - os: linux
      dist: focal
      compiler: gcc
      env: RENDERER=vulkan CONFIG=Release GCC=10 Y3=jpeg,vorbis
      addons: &gcc_xcb_vulkan
        apt:
          packages:
            - g++-10
            - libasound2-dev
            - libvorbis-dev
            - libvulkan-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - glslang-dev
            - spirv-tools
            - yasm
            - ninja-build

    - os: linux
      dist: focal
      compiler: gcc
      env: RENDERER=vulkan CONFIG=Debug GCC=10 Y3=jpeg,vorbis
      addons: *gcc_xcb_vulkan

    - os: linux
      dist: focal
      compiler: clang
      env: RENDERER=vulkan CONFIG=Release CLANG=11 Y3=jpeg,vorbis
      addons: &clang_xcb_vulkan
        apt:
          packages:
            - clang-11
            - libasound2-dev
            - libstdc++-10-dev
            - libvorbis-dev
            - libvulkan-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - glslang-dev
            - spirv-tools
            - nasm
            - ninja-build

    - os: linux
      dist: focal
      compiler: clang
      env: RENDERER=vulkan CONFIG=Debug CLANG=11 Y3=jpeg,vorbis
      addons: *clang_xcb_vulkan

    - os: linux
      dist: focal
      compiler: gcc
      env: RENDERER=null CONFIG=Debug GCC=10 Y3=jpeg,vorbis COVERAGE=1
      addons:
        apt:
          packages:
            - g++-10
            - libasound2-dev
            - libvorbis-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - yasm
            - ninja-build

before_install:
  - if [ -n "${CLANG}" ]; then export CC=clang-${CLANG} CXX=clang++-${CLANG}; fi
  - if [ -n "${GCC}" ]; then export ASM_NASM=$(which yasm) CC=gcc-${GCC} CXX=g++-${GCC} LDFLAGS=-fuse-ld=gold; fi
  - ${CXX} --version
  - cmake --version

install:
  - mkdir "${HOME}/y3.prefix" && pushd "${HOME}/y3.prefix"
  - cmake -DBUILD=${Y3} -DCACHE="${HOME}/y3.cache" -DCONFIG=${CONFIG} -P "${TRAVIS_BUILD_DIR}/cmake/y3/get.cmake"
  - popd
  - if [ -n "${COVERAGE}" ]; then pip install --user codecov; fi

script:
  - if [ -z "${COVERAGE}" ]; then CMAKE_OPTIONS+=" -DBUILD_EXAMPLES=ON -DINSTALL_EXAMPLES=ON"; fi
  - if [ -z "${ANALYZE}" ] && [ -z "${COVERAGE}" ]; then CMAKE_OPTIONS+=" -DENABLE_SANITIZERS=ON"; fi
  - if [ -n "${ANALYZE}" ]; then CMAKE_OPTIONS+=" -DENABLE_CLANG_TIDY=ON"; fi
  - if [ -n "${COVERAGE}" ]; then CMAKE_OPTIONS+=" -DENABLE_COVERAGE=ON"; fi
  - cmake -H. -B"${HOME}/yttrium.build" -G"Ninja" -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_INSTALL_PREFIX="${HOME}/yttrium.install" -DCMAKE_PREFIX_PATH="${HOME}/y3.prefix" -DY_RENDERER=${RENDERER} ${CMAKE_OPTIONS}
  - if [ -n "${ANALYZE}" ]; then cppcheck --enable=all --error-exitcode=1 --inline-suppr --quiet -I "${TRAVIS_BUILD_DIR}/libs/audio/include" -I "${TRAVIS_BUILD_DIR}/libs/core/include" -I "${TRAVIS_BUILD_DIR}/libs/engine/include" -i "${HOME}/yttrium.build/CMakeFiles" --include="${HOME}/yttrium.build/config.h" --relative-paths="${TRAVIS_BUILD_DIR}" --suppressions-list="${TRAVIS_BUILD_DIR}/.cppcheck-suppress" --template="({file},{line}) ({severity}/{id}) {message}" "${TRAVIS_BUILD_DIR}"; fi
  - if [ -n "${ANALYZE}" ]; then cmake --build "${HOME}/yttrium.build" --target tidy; fi
  - if [ -n "${ANALYZE}" ]; then clang-format-${CLANG} -i $(find ${TRAVIS_BUILD_DIR} -type f \( -name '*.cpp' -o -name '*.h' \) -printf ' %p'); fi
  - if [ -n "${ANALYZE}" ]; then git diff --color=always --exit-code --histogram; fi
  - pushd "${HOME}/yttrium.build"
  - if [ -z "${ANALYZE}" ]; then TERM=dumb cmake --build .; fi
  - if [ -z "${ANALYZE}" ]; then ctest --output-on-failure; fi
  - if [ -z "${ANALYZE}" ] && [ -z "${COVERAGE}" ]; then cmake --build . --target install; fi
  - popd

after_success:
  - if [ -n "${COVERAGE}" ]; then codecov --gcov-root "${HOME}/yttrium.build" --gcov-exec gcov-${GCC} --gcov-args "-s `pwd`"; fi

notifications:
  email: false
