language: cpp
dist: trusty
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libopenal-dev
      - libvorbis-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      env: GCC_VERSION=6

before_install:
  - if [ "${GCC_VERSION}" != "" ]; then export CC=gcc-$GCC_VERSION CXX=g++-$GCC_VERSION; fi

install:
  - mkdir ${TRAVIS_BUILD_DIR}/travis

  - mkdir ${TRAVIS_BUILD_DIR}/travis/boost && pushd ${TRAVIS_BUILD_DIR}/travis/boost
  - wget -q -O - http://downloads.sourceforge.net/project/boost/boost/1.64.0/boost_1_64_0.tar.bz2 | tar -xj --strip-components 1
  - ./bootstrap.sh
  - ./b2 headers
  - CMAKE_OPTIONS+=" -DBOOST_ROOT=$(pwd)"
  - popd

  - mkdir ${TRAVIS_BUILD_DIR}/travis/cmake && pushd ${TRAVIS_BUILD_DIR}/travis/cmake
  - wget -q --no-check-certificate -O - https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz | tar -xz --strip-components 1
  - export PATH=$(pwd)/bin:${PATH}
  - popd

script:
  - cmake . $CMAKE_OPTIONS
  - make
