language: cpp
dist: trusty
sudo: false

git:
  depth: 1

matrix:
  include:

    # Gcov 8 generates a tremendous amount of warnings which gets our job killed.
    - os: linux
      compiler: gcc
      env: GCC_V=7 CONFIG=Debug RENDERER=Null Y3=catch2 COVERAGE=1
      addons: &gcc7_xcb
        apt:
          sources: &all_sources
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libopenal-dev
            - libvorbis-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev

    - os: linux
      compiler: gcc
      env: GCC_V=8 CONFIG=Release RENDERER=OpenGL Y3=catch2
      addons: &gcc8_x11
        apt:
          sources: *all_sources
          packages:
            - g++-8
            - libopenal-dev
            - libvorbis-dev

    - os: linux
      compiler: gcc
      env: GCC_V=8 CONFIG=Debug RENDERER=OpenGL Y3=catch2
      addons: *gcc8_x11

    - os: linux
      compiler: gcc
      env: GCC_V=8 CONFIG=Release RENDERER=Vulkan Y3=catch2,glslang,vulkan
      addons: &gcc8_xcb
        apt:
          sources: *all_sources
          packages:
            - g++-8
            - libopenal-dev
            - libvorbis-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev

    - os: linux
      compiler: gcc
      env: GCC_V=8 CONFIG=Debug RENDERER=Vulkan Y3=catch2,glslang,vulkan
      addons: *gcc8_xcb

    - os: linux
      compiler: clang
      env: CLANG_V=6.0 CONFIG=Release RENDERER=Null Y3=catch2
      addons: &clang6_xcb
        apt:
          sources: *all_sources
          packages:
            - clang-6.0
            - libopenal-dev
            - libstdc++-8-dev
            - libvorbis-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev

    - os: linux
      compiler: clang
      env: CLANG_V=6.0 CONFIG=Debug RENDERER=Null Y3=catch2
      addons: *clang6_xcb

before_install:
  - if [ -n "${CLANG_V}" ]; then export CC=clang-$CLANG_V CXX=clang++-$CLANG_V; fi
  - if [ -n "${GCC_V}" ]; then export CC=gcc-$GCC_V CXX=g++-$GCC_V; fi

install:
  - mkdir _cmake && pushd _cmake
  - wget -q --no-check-certificate -O - https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.tar.gz | tar -x --gzip --strip-components 1
  - export PATH=$(pwd)/bin:${PATH}
  - popd

  - mkdir _prefix && pushd _prefix
  - cmake -DBUILD=${Y3} -DCONFIG=${CONFIG} -P ../bootstrap/get.cmake
  - popd

script:
  - mkdir _build && pushd _build
  - if [ -z "${COVERAGE}" ]; then CMAKE_OPTIONS+=" -DY_BUILD_ALL=ON"; fi
  - if [ -n "${COVERAGE}" ]; then CMAKE_OPTIONS+=" -DY_BUILD_TESTS=ON -DY_COVERAGE=ON"; fi
  - cmake .. -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/_prefix $CMAKE_OPTIONS -DY_RENDERER=$RENDERER
  - cmake --build . -- -j2
  - cmake --build . --target check
  - popd

after_success:
  - if [ -n "${COVERAGE}" ]; then bash <(curl -s https://codecov.io/bash) -x gcov-$GCC_V -a "-s `pwd`"; fi

notifications:
  email: false
