language: cpp

git:
  depth: 1

matrix:
  include:

    - os: linux
      dist: bionic
      compiler: clang
      env: CLANG=9 CONFIG=Debug DLL=ON RENDERER=null Y3=aulos,catch2,cppcheck,jpeg ANALYZE=1
      addons:
        apt:
          sources: &all_sources
            - ubuntu-toolchain-r-test
          packages:
            - clang-9
            - clang-format-9
            - clang-tidy-9
            - libasound2-dev
            - libstdc++-10-dev
            - libvorbis-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - nasm
            - ninja-build

    - os: linux
      dist: bionic
      compiler: gcc
      env: GCC=10 CONFIG=Release DLL=OFF RENDERER=null Y3=aulos,catch2,jpeg
      addons: &gcc_xcb
        apt:
          sources: *all_sources
          packages:
            - g++-10
            - libasound2-dev
            - libvorbis-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - yasm
            - ninja-build

    - os: linux
      dist: bionic
      compiler: gcc
      env: GCC=10 CONFIG=Debug DLL=ON RENDERER=null Y3=aulos,catch2,jpeg,lcov COVERAGE=1
      addons: *gcc_xcb

    - os: linux
      dist: bionic
      compiler: gcc
      env: GCC=10 CONFIG=Release DLL=OFF RENDERER=opengl Y3=aulos,catch2,jpeg
      addons: &gcc_x11
        apt:
          sources: *all_sources
          packages:
            - g++-10
            - libasound2-dev
            - libgl-dev
            - libvorbis-dev
            - yasm
            - ninja-build

    - os: linux
      dist: bionic
      compiler: gcc
      env: GCC=10 CONFIG=Debug DLL=ON RENDERER=opengl Y3=aulos,catch2,jpeg
      addons: *gcc_x11

    - os: linux
      dist: bionic
      compiler: gcc
      env: GCC=10 CONFIG=Release DLL=OFF RENDERER=vulkan Y3=aulos,catch2,glslang,jpeg,vulkan
      addons: *gcc_xcb

    - os: linux
      dist: bionic
      compiler: gcc
      env: GCC=10 CONFIG=Debug DLL=ON RENDERER=vulkan Y3=aulos,catch2,glslang,jpeg,vulkan
      addons: *gcc_xcb

    - os: linux
      dist: bionic
      compiler: clang
      env: CLANG=9 CONFIG=Release DLL=OFF RENDERER=null Y3=aulos,catch2,jpeg
      addons: &clang_xcb
        apt:
          sources: *all_sources
          packages:
            - clang-9
            - libasound2-dev
            - libstdc++-10-dev
            - libvorbis-dev
            - libxcb-image0-dev
            - libxcb-xkb-dev
            - libxkbcommon-dev
            - libxkbcommon-x11-dev
            - nasm
            - ninja-build

    - os: linux
      dist: bionic
      compiler: clang
      env: CLANG=9 CONFIG=Release DLL=OFF RENDERER=opengl Y3=aulos,catch2,jpeg
      addons: &clang_x11
        apt:
          sources: *all_sources
          packages:
            - clang-9
            - libasound2-dev
            - libgl-dev
            - libstdc++-10-dev
            - libvorbis-dev
            - nasm
            - ninja-build

    - os: linux
      dist: bionic
      compiler: clang
      env: CLANG=9 CONFIG=Debug DLL=ON RENDERER=opengl Y3=aulos,catch2,jpeg
      addons: *clang_x11

    - os: linux
      dist: bionic
      compiler: clang
      env: CLANG=9 CONFIG=Release DLL=OFF RENDERER=vulkan Y3=aulos,catch2,glslang,jpeg,vulkan
      addons: *clang_xcb

    - os: linux
      dist: bionic
      compiler: clang
      env: CLANG=9 CONFIG=Debug DLL=ON RENDERER=vulkan Y3=aulos,catch2,glslang,jpeg,vulkan
      addons: *clang_xcb

before_install:
  - mkdir "${HOME}/_cmake" && pushd "${HOME}/_cmake"
  - wget --output-document=- --quiet https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz | tar -x --gzip --strip-components 1
  - export PATH="$(pwd)/bin:${PATH}"
  - popd
  - if [ -n "${CLANG}" ]; then export CC=clang-${CLANG} CXX=clang++-${CLANG}; fi
  - if [ -n "${GCC}" ]; then export ASM_NASM=$(which yasm) CC=gcc-${GCC} CXX=g++-${GCC} LDFLAGS=-fuse-ld=gold; fi

install:
  - mkdir "${HOME}/y3.prefix" && pushd "${HOME}/y3.prefix"
  - cmake -DBUILD=${Y3} -DCACHE="${HOME}/y3.cache" -DCONFIG=${CONFIG} -DPIC=${DLL} -P "${TRAVIS_BUILD_DIR}/cmake/y3/get.cmake"
  - popd
  - if [ -n "${COVERAGE}" ]; then pip install --user codecov; fi

script:
  - if [ -z "${COVERAGE}" ]; then CMAKE_OPTIONS+=" -DBUILD_EXAMPLES=ON -DINSTALL_EXAMPLES=ON"; fi
  - if [ -z "${ANALYZE}" ] && [ -z "${COVERAGE}" ]; then CMAKE_OPTIONS+=" -DENABLE_SANITIZERS=ON"; fi
  - if [ -n "${ANALYZE}" ]; then CMAKE_OPTIONS+=" -DENABLE_CLANG_FORMAT=ON -DENABLE_CLANG_TIDY=ON -DENABLE_CPPCHECK=ON -DENABLE_DIFF=ON"; fi
  - if [ -n "${COVERAGE}" ]; then CMAKE_OPTIONS+=" -DENABLE_COVERAGE=ON -DENABLE_COVERAGE_LCOV=ON"; fi
  - cmake -H. -B"${HOME}/yttrium.build" -G"Ninja" -DBUILD_SHARED_LIBS=${DLL} -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_INSTALL_PREFIX="${HOME}/yttrium.install" -DCMAKE_PREFIX_PATH="${HOME}/y3.prefix" -DY_RENDERER=${RENDERER} -DY_USE_OGG_VORBIS=OFF ${CMAKE_OPTIONS}
  - pushd "${HOME}/yttrium.build"
  - if [ -n "${ANALYZE}" ]; then cmake --build . --target cppcheck; fi
  - if [ -n "${ANALYZE}" ]; then cmake --build . --target tidy; fi
  - if [ -n "${ANALYZE}" ]; then cmake --build . --target format; fi
  - if [ -n "${ANALYZE}" ]; then cmake --build . --target diff; fi
  - if [ -z "${ANALYZE}" ]; then TERM=dumb cmake --build .; fi
  - if [ -z "${ANALYZE}" ]; then ctest --output-on-failure; fi
  - if [ -z "${ANALYZE}" ] && [ -z "${COVERAGE}" ]; then cmake --build . --target install; fi
  # lcov 1.14 doesn't work with GCC 9.x, see https://github.com/linux-test-project/lcov/issues/58
  #- if [ -n "${COVERAGE}" ]; then cmake --build . --target lcov; fi
  - popd

after_success:
  - if [ -n "${COVERAGE}" ]; then codecov --gcov-root "${HOME}/yttrium.build" --gcov-exec gcov-${GCC} --gcov-args "-s `pwd`"; fi

notifications:
  email: false
