language: c++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libopenal-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      env: GCC_VERSION=6

before_install:
  - if [ "${GCC_VERSION}" != "" ]; then export CC=gcc-$GCC_VERSION CXX=g++-$GCC_VERSION; fi

install:
  - mkdir ${TRAVIS_BUILD_DIR}/travis
  - mkdir ${TRAVIS_BUILD_DIR}/travis/cmake
  - wget -q --no-check-certificate -O - https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz | tar -xz -C ${TRAVIS_BUILD_DIR}/travis/cmake --strip-components 1
  - export PATH=${TRAVIS_BUILD_DIR}/travis/cmake/bin:${PATH}

script:
  - cmake .
  - make
  - make check
