Import('env')

build = env.Clone(BUILD = '.build')

build.Append(
	CPPDEFINES = 'BOOST_TEST_DYN_LINK',
	LIBS = 'boost_unit_test_framework')

build.VariantDir('$BUILD', '.', duplicate = 0)

# The order is important!

test_paths = [
	'static_string',
	'ion',
	'image']

tests = []

for test_path in test_paths:
	test = build.Program('#/bin/tests/' + test_path, build.Glob('$BUILD/' + test_path + '/*.cpp'))
	build.Clean(test, build.Dir('$BUILD'))
	tests += [test]

Return('tests')
