import os
import os.path

Import('env')

tools = []
for tool_path in [path for path in os.listdir('.') if os.path.isdir(path) and path[0] != '.']:
	tools += [env.SConscript(dirs = tool_path, exports = 'env')]

Return('tools')
