function(append_options _variable)
	string(REPLACE ";" " " _value "${ARGN}")
	if(NOT "${${_variable}}" STREQUAL "")
		set(_separator " ")
	else()
		set(_separator "")
	endif()
	set(${_variable} "${${_variable}}${_separator}${_value}" PARENT_SCOPE)
endfunction()

function(print_list _prefix)
	message(STATUS "${_prefix}")
	if(NOT "${ARGN}" STREQUAL "")
		string(REPLACE ";" " " text " ${ARGN}")
		message(STATUS " ${text}")
	else()
		message(STATUS "  (none)")
	endif()
endfunction()
